### ISSUE TITLE
Adding a button on top and title on bottom

### ISSUE THREAD

**Issue by mding5692** [terenceLuffy/AppStoreStyleHorizontalScrollView#23]
Hi, really appreciate the good work, is there a way to put a button on top and an label at the bottom like the instagram stories like below?

![screen shot 2017-06-13 at 9 47 34 pm](https://user-images.githubusercontent.com/9067177/27111980-ef4376b4-5081-11e7-9c45-d8f1b06ba6eb.png)

This is what happens after I used addItem on both the button and label:
![screen shot 2017-06-13 at 9 46 44 pm](https://user-images.githubusercontent.com/9067177/27111965-deb3d8fc-5081-11e7-8010-e27fb57aa722.png)

Much thanks!

**Comment by terenceLuffy** [comment]
Create a UIView as container, add button and label in the container, add the container as item.

**Comment by mding5692** [comment]
oh ok thanks :)

**Comment by asteiman** [comment]
Hi, I am trying exactly what you suggested, and I am struggling a little bit.

Here is the code:
```
for _ in 1...5 {
    let view = UIView.init()
    let label = UILabel.init()
    label.text = "test" + String(arc4random())
    label.translatesAutoresizingMaskIntoConstraints = false
    label.textColor = UIColor.black
            
    view.addSubview(label)
            
    view.addConstraint(NSLayoutConstraint.init(item: label, attribute: NSLayoutAttribute.width, relatedBy: NSLayoutRelation.equal, toItem: nil, attribute: NSLayoutAttribute.notAnAttribute, multiplier: 1, constant: 150))
    view.addConstraint(NSLayoutConstraint.init(item: label, attribute: NSLayoutAttribute.height, relatedBy: NSLayoutRelation.equal, toItem: nil, attribute: NSLayoutAttribute.notAnAttribute, multiplier: 1, constant: 20))

    view.backgroundColor = UIColor.gray
    horizontalScrollView.addItem(view)
}
```
And the result is:
![1](https://user-images.githubusercontent.com/1952395/27256626-f1f65654-53cb-11e7-9c01-47fdeb4a837d.gif)

All the labels are misaligned. So I added the following 2 lines, so the `label` is at the corner of each `view` instead of the `scrollView`
```
(...)
view.addConstraints(NSLayoutConstraint.constraints(withVisualFormat: "V:|[label]", options: [], metrics: nil, views: ["label": label]))
view.addConstraints(NSLayoutConstraint.constraints(withVisualFormat: "H:|[label]", options: [], metrics: nil, views: ["label": label]))

view.backgroundColor = UIColor.gray
horizontalScrollView.addItem(view)
```
And all the views disappeared, just blank screen, and nothing in the console.
So I added `card.translatesAutoresizingMaskIntoConstraints = false` because its breaking when trying to link the `label` with it's superview `view`, and I get the following result:

![2](https://user-images.githubusercontent.com/1952395/27256643-1d9a2cb2-53cd-11e7-9b8e-b868cbf9e5f6.gif)
The labels appeared again, still at wrong place, the scrollview broke, and the gray color also vanished.

Do you know what might be happening? could be the fact that all the scrollview is build using frames, and is not compatible with constraints?
Maybe you can share the snippet you used on the `README`

Thanks,
Alan

**Comment by terenceLuffy** [comment]
@asteiman What size do you set for uniformSize for item? It looks like the item size is zero. And the constraints you add to label is not enough, besides width and height, you also need to add position constraints too.

**Comment by asteiman** [comment]
@terenceLuffy thanks for you quick response. I changed the width and height constraint to the label now. With the following code, I get blank, no views:

```
let horizontalScrollView:ASHorizontalScrollView = ASHorizontalScrollView(frame:CGRect(x: 0, y: 0, width: 320, height: 120))
        
horizontalScrollView.defaultMarginSettings = MarginSettings(leftMargin: 10, miniMarginBetweenItems: 1, miniAppearWidthOfLastItem: 15)
        
horizontalScrollView.uniformItemSize = CGSize(width: 294, height: 120)
        
horizontalScrollView.setItemsMarginOnce()
for _ in 1...5 {
    let view = UIView.init()
    let label = UILabel.init()
    label.text = "test" + String(arc4random())
    label.translatesAutoresizingMaskIntoConstraints = false
    label.textColor = UIColor.black
            
    view.addSubview(label)
            
    label.addConstraint(NSLayoutConstraint.init(item: label, attribute: NSLayoutAttribute.width, relatedBy: NSLayoutRelation.equal, toItem: nil, attribute: NSLayoutAttribute.notAnAttribute, multiplier: 1, constant: 150))
    label.addConstraint(NSLayoutConstraint.init(item: label, attribute: NSLayoutAttribute.height, relatedBy: NSLayoutRelation.equal, toItem: nil, attribute: NSLayoutAttribute.notAnAttribute, multiplier: 1, constant: 20))
            
    view.addConstraints(NSLayoutConstraint.constraints(withVisualFormat: "V:|[label]", options: [], metrics: nil, views: ["label": label]))
    view.addConstraints(NSLayoutConstraint.constraints(withVisualFormat: "H:|[label]", options: [], metrics: nil, views: ["label": label]))
            
            
    view.backgroundColor = UIColor.gray
    horizontalScrollView.addItem(view)
}
        
self.contentView.addSubview(horizontalScrollView)
```

However, If i change the width of `uniformItemSize` to `295` instead of `294`, I get the following:
![3](https://user-images.githubusercontent.com/1952395/27259102-4c1a264c-541c-11e7-80c6-7cc5d980b43a.gif)

`label` is well positioned apparently, however I am not able to scroll through the other 4 views.

Thanks,
Alan

**Comment by terenceLuffy** [comment]
Did you use my sample project for testing? I just found my constraints on contentView is not enough too. Add the following two lines should make it works:

        cell?.contentView.addConstraint(NSLayoutConstraint(item: horizontalScrollView, attribute: NSLayoutAttribute.left, relatedBy: NSLayoutRelation.equal, toItem: cell!.contentView, attribute: NSLayoutAttribute.left, multiplier: 1, constant: 0))
            cell?.contentView.addConstraint(NSLayoutConstraint(item: horizontalScrollView, attribute: NSLayoutAttribute.top, relatedBy: NSLayoutRelation.equal, toItem: cell!.contentView, attribute: NSLayoutAttribute.top, multiplier: 1, constant: 0))

**Comment by mding5692** [comment]
@terenceLuffy Thanks terence for your work :)
